CREATE DATABASE OnlineForum;

--Creating a table with user login credentials
CREATE TABLE Users(
Id int identity(1,1) PRIMARY KEY,
Name VARCHAR(30),
Email VARCHAR(90) UNIQUE,
Password VARCHAR(15) UNIQUE,
SecurityQn VARCHAR(MAX),
SecurityAns VARCHAR(225));


--Creating a table with Discussion Forum
CREATE TABLE Forum(
ForumId INT IDENTITY(1,1) PRIMARY KEY,
--Id means UserId 
Id INT NOT NULL,
Category NVARCHAR(70) NOT NULL,
Title NVARCHAR(125) UNIQUE NOT NULL,
Content NVARCHAR(MAX) NOT NULL,
CreatedDate DATETIME DEFAULT SYSDATETIME() NOT NULL,
CONSTRAINT fk_Id FOREIGN KEY (Id) REFERENCES Users(Id) );

--Creating a tale for replies
CREATE TABLE Replies(
ReplyId INT IDENTITY(1,1) PRIMARY KEY,
ForumId INT NOT NULL,
Id INT NOT NULL,
ReplyContent NVARCHAR(MAX) NOT NULL,
RelpyCreated DATETIME DEFAULT SYSDATETIME() NOT NULL,
CONSTRAINT fk_UserID FOREIGN KEY (Id) REFERENCES Users(Id),
CONSTRAINT fk_ForumId FOREIGN KEY (ForumId) REFERENCES Forum(ForumId));

DROP TABLE PollResult;

--Creating a table for Polls
CREATE TABLE Polls(
PollId INT IDENTITY(1,1) PRIMARY KEY,
--Id means UserId 
Id INT NOT NULL,
Category NVARCHAR(70) NOT NULL,
PollTitle NVARCHAR(125) UNIQUE NOT NULL,
CreatedDate DATETIME DEFAULT SYSDATETIME() NOT NULL,
CONSTRAINT fk_Id_For_Polls FOREIGN KEY (Id) REFERENCES Users(Id) );

--Creating a table PollResult
CREATE TABLE PollResult(
PollRes_Id INT IDENTITY(1,1) PRIMARY KEY,
PollId INT NOT NULL,
UserId INT NOT NULL,
VoteOptions NVARCHAR(200) NOT NULL,
VoteDate DATETIME DEFAULT SYSDATETIME() NOT NULL,
CONSTRAINT fk_pollRes_id FOREIGN KEY (UserId) REFERENCES Users(Id),
CONSTRAINT fk_PollId FOREIGN KEY (PollId) REFERENCES Polls(PollId)
);


 CREATE TABLE Memory(
 Memory_Id INT IDENTITY(1,1) PRIMARY KEY,
 UserId INT NOT NULL,
 Title NVARCHAR(200) NOT NULL,
 Description NVARCHAR(MAX) NOT NULL,
 MemoryDate DATETIME DEFAULT SYSDATETIME() NOT NULL,
 CONSTRAINT fk_mem_USERID FOREIGN KEY(UserId) REFERENCES Users(Id));


 SELECT * FROM Users;
 SELECT * FROM Forum;
 SELECT * FROM Replies;
 SELECT * FROM PollResult;
 SELECT * FROM Polls;
 SELECT * FROM Memory;
